[package]
name = "hungarian"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]

[dependencies]
fnv = "1.0.6"
fixedbitset = "0.1.8"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmark"
harness = false
